mutation($input: IssueInput!) {
	updateIssue(input: $input) {
    id
    key
    title
    volume
    number
    year
    body
    evaluationPeriod
    publicationPrediction
    contact
    publishedCall
    published
    startCall
    endCall
  }
}