mutation($input: IssueUpdateInput! $issueId: ID!) {
	updateIssue(input: $input issueId: $issueId) {
    id
    key
    title
    volume
    number
    year
    body
    evaluationPeriod
    publicationPrediction
    contact
    publishedCall
    published
    startCall
    endCall
  }
}